In [5]:
import numpy as np

# Create a 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calculate the sum of each row
row_sums = np.sum(array, axis=1)

print("2D Array:")
print(array)
print("Sum of each row:")
print(row_sums)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of each row:
[ 6 15 24]
